config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get '/search', to: 'recommendations#search'
  post '/search', to: 'recommendations#create'

  get '/search/:id/recommendations', to: 'recommendations#index', as: 'search_result'
  get '/search/:id/recommendations/:id', to: 'recommendations#show', as: 'search_result_details'
  delete '/search/:search_id/recommendations/:id/delete', to: 'recommendations#destroy', as: 'destroy_recommendation'
  post '/search/:id/recommendations/:id', to: 'recommendations#add_recommendations', as: 'add_recommendations_to_watch_list'

  get '/user', to: 'pages#user_page', as: 'watchlist'
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  has_many :recommendation_watch_lists, dependent: :destroy
  has_many :watch_lists, through: :recommendation_watch_lists

  belongs_to :query
  belongs_to :user
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  OMDB_API_KEY = ENV['OMDB_API_KEY']
  X_RAPIDAPI_KEY = ENV['X_RAPIDAPI_KEY']
  X_RAPIDAPI_HOST = ENV['X_RAPIDAPI_HOST']

  def search
    @genres = Query::GENRES
    @user = current_user
    @query = Query.new
  end

  def create
    @genres = Query::GENRES
    @query = Query.new(query_params)
    @query.medium = "movie and tv show" if @query.medium.nil?
    @query.user = current_user
    if @query.save
      redirect_to search_result_path(@query)
      create_openai_request(@query)
    else
      render :search
    end
  end

  def index
    @query = Query.find(params[:id])
    @query.medium = "movie and tv show" if @query.medium.nil?
    @mood = Query::MOOD[@query.happiness]
    @desired_mood = Query::MOOD[@query.desired_happiness]
    @display_prompt = create_display_prompt(@query, @mood, @desired_mood)
    @recommendations = Recommendation.where(query_id: @query.id)
    @watch_list_movies = WatchList.where(user: current_user)
    @watch_list = RecommendationWatchList.where(watch_list: @watch_list_movies)
  end

  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy
  end

  def show
    @recommendation = Recommendation.find(params[:id])
    get_streaming_availability(@recommendation.imdbID)

    @watch_list_movies = WatchList.where(user: current_user)
    @watch_list = RecommendationWatchList.where(watch_list: @watch_list_movies)
    @watch_list = @watch_list.map { |watch_list| watch_list.recommendation }
    @watch_list = @watch_list.filter { |recommendation| recommendation.movie_name == @recommendation.movie_name }
  end

  def add_recommendations
    @recommendation = Recommendation.find(params[:id])
    @watch_list = WatchList.find_by_id(user: current_user)
    @watch_list ||= WatchList.new(user: current_user)
    @recommendation.watch_lists << @watch_list

    if @recommendation.save
      @watch_list.save
    else
      flash[:alert] = "Something went wrong. Please try again."
    end
  end

  private

  def query_params
    params.require(:query).permit(
      :user_id, :time, :year_after, :year_before, :year_option, :happiness, :desired_happiness,
      :intensity, :novelty, :recent_movie1, :recent_movie2, :recent_movie3,
      :other, :audience, :medium
    ).tap do |query_params|
      query_params[:genre] = sanitize_params(params[:query][:genre])
      query_params[:streaming_platform] = sanitize_params(params[:query][:streaming_platform])
    end
  end

  def sanitize_params(params)
    params.reject { |_, value| value == "0" }.keys.join(", ")
  end

  def create_prompt(query, mood, desired_mood)
    prompt_parts = [
      "Show me a list of 10 real #{query.medium}s. Just display the titles in a hash format like: { \"#{query.medium}1\": \"#{query.medium} name\", ... }.",
      "Always list existing #{query.medium}s, NOT your preference.",
      "Remember to use double quotation marks to wrap the #{query.medium} name, but use single quotation marks within the #{query.medium} names.",
      "Do NOT include the #{query.medium} year or episode information.",
      "Here's some information about me:",
      ("I want to spend around #{query.time} minutes watching a #{query.medium}." if query.time.present? && query.time != 70 && query.time != 120),
      ("I enjoy #{query.genre} #{query.medium}s." if query.genre.present?),
      ("I'm currently feeling #{mood} and I'm in the mood for a #{query.medium} that makes me feel #{desired_mood}." if (query.desired_happiness.present? && query.happiness.present?) && ((query.desired_happiness < 4 || query.desired_happiness > 7) && (query.happiness < 4 || query.happiness > 7))),
      ("I'm currently feeling #{mood}" if (mood.present? && (query.happiness < 4 || query.happiness > 7))),
      ("I want to feel #{desired_mood}." if (desired_mood.present? && (query.desired_happiness < 4 || query.desired_happiness > 7))),
      ("I'm planning to watch this #{query.medium} with my partner." if query.audience == "Couple"),
      ("I'm planning to watch this #{query.medium} with my family." if query.audience == "Family"),
      ("I'm planning to watch this #{query.medium} by myself." if query.audience == "Just me"),
      ("I prefer a #{query.medium} where I don't have to concentrate too much." if query.intensity.present? && query.intensity < 4),
      ("I prefer a #{query.medium} that requires deep concentration." if query.intensity.present? && query.intensity > 7),
      ("The #{query.medium} should be originally released between #{query.year_after} and #{query.year_before}." if query.year_after != 1950 && query.year_before != 2023),
      ("I'm in the mood for something more experimental." if query.novelty.present? && query.novelty > 7),
      ("I'm in the mood for something more mainstream." if query.novelty.present? && query.novelty < 4),
      ("I really enjoyed watching #{query.recent_movie1}, #{query.recent_movie2}, and #{query.recent_movie3}. It would be great to find something similar now." if query.recent_movie1.present? || query.recent_movie2.present? || query.recent_movie3.present?),
      ("Consider my previous movie choices, but don't suggest them to me again." if query.recent_movie1.present? || query.recent_movie2.present? || query.recent_movie3.present?),
      ("Here's some additional information about myself and my day that can help you filter this #{query.medium}: #{query.other}." if query.other.present?),
      ("I have access to the following streaming platforms: #{query.streaming_platform}." if query.streaming_platform.present?),
      ("Please take into account all the information I provided and consider multiple aspects."),
      "Show me a list of 10 real #{query.medium}s. Just display the titles in a hash format like: { \"#{query.medium}1\": \"#{query.medium} name\", ... }.",
    ]
    prompt_parts.compact.join("\n")
    p prompt_parts.compact.join("\n")
  end

  def create_display_prompt(query, mood, desired_mood)
    prompt = ""
    prompt += "Hi! Looks like you're searching for a #{query.medium.downcase} recommendation.\n" if query.medium.present?
    prompt += "Since you're a bit short on time, I've got some shorter #{query.medium.downcase}s lined up for you.\n" if query.time.present? && query.time < 90 && query.medium == "Movie"
    prompt += "Since you have plenty of time on your hands, I've picked out some longer #{query.medium.downcase}s for you.\n" if query.time.present? && query.time > 90 && query.medium == "Movie"
    prompt += "I've tried my best to find #{query.medium.downcase}s that you can enjoy together with your partner.\n" if query.audience == "Couple"
    prompt += "I've tried my best to find #{query.medium.downcase}s that you can enjoy with your whole family.\n" if query.audience == "Family"
    prompt += "I've tried my best to find #{query.medium.downcase}s that you can enjoy all by yourself.\n" if query.audience == "Just me"
    prompt += "I get the sense that you're feeling #{mood.downcase} and want to feel #{desired_mood.downcase}. I hope I can help you with that.\n" if mood.present? && desired_mood.present?
    prompt += "I get the sense that you're feeling #{mood.downcase}.\n" if mood.present? && desired_mood.nil?
    prompt += "I get the sense that you want to feel #{desired_mood.downcase}. I hope I can help you with that.\n" if desired_mood.present? && mood.nil?
    prompt += "I've discovered some more experimental #{query.medium.downcase}s that might satisfy your craving for novelty.\n" if query.novelty.present? && query.novelty > 7
    prompt += "Some of the #{query.medium.downcase}s I choose for you share some similarities with #{query.recent_movie1}.\n" if query.recent_movie1.present?
    prompt += "Some of the #{query.medium.downcase}s I choose for you share some similarities with #{query.recent_movie1} and #{query.recent_movie2}.\n" if query.recent_movie1.present? && query.recent_movie2.present?
    prompt += "Enjoy your #{query.medium.downcase} and let me know how you liked my recommendations!\n"
    prompt
  end

  def create_recommendation(response, query)
    response.each do |_key, value|
      data = create_omdb_request(value)
      next if data.nil?

      create_recommendation_class(data, query)&.tap(&:save)
    end
  end

  def create_recommendation_class(data, query)
    Recommendation.new(
      user: current_user,
      movie_name: data['Title'],
      imdbID: data['imdbID'],
      genre: data['Genre'],
      year: data['Year'],
      rating: data['Rated'],
      image: data['Poster'],
      awards: data['Awards'],
      runtime: data['Runtime'],
      synopsis: data['Plot'],
      director: data['Director'],
      writer: data['Writer'],
      actors: data['Actors'],
      imdb_score: data['imdbRating'].present? ? data['imdbRating'] : nil,
      query_id: query
    )
  end

  def get_streaming_availability(imdbID)
    url = URI("https://streaming-availability.p.rapidapi.com/v2/get/basic?country=de&imdb_id=#{imdbID}&output_language=en")
    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = X_RAPIDAPI_KEY
    request["X-RapidAPI-Host"] = X_RAPIDAPI_HOST
    response = Net::HTTP.start(url.hostname, url.port, use_ssl: true) do |http|
      http.request(request)
    end
    @data = JSON.parse(response.body)
    # @data = {
    #   "result" => {
    #   "type" => "movie",
    #   "title" => "The Dark Knight",
    #   "overview" => "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    #   "streamingInfo" => {
    #     "de" => {
    #       "hbo" => [
    #         {
    #           "type" => "subscription",

app/views/recommendations/_movie_card.html.erb
<% if movie['movie_name'] != nil %>
  <div class="movie-card">
    <%= link_to 'X', destroy_recommendation_path(search_id: params[:id], id: movie.id), remote: true, data: {turbo_method: :delete, action: "click->view-more#remove", index: index, view_more_target: "remove"}, class: 'movie-card-delete-button' %>
    <%= image_tag movie['image'] && movie['image'] != 'N/A' ? movie['image'] : '', alt: movie['movie_name']  %>
    <div class="movie-card-infos-container">
      <h1 class="movie-card-infos-container-title"><%= movie['movie_name'] %> ( <%= movie['year'] %> )</h1>
      <p class="movie-card-infos-container-description"><%= movie['synopsis'] && movie['synopsis'] != 'N/A' ? movie['synopsis'] : "The #{ movie['movie_name'] } no have description for now!" %></p>
      <div class="movie-card-infos-container-buttons-container">
        <%= link_to "Learn more", "/search/#{@query.id}/recommendations/#{movie.id}", class: "movie-card-button"%>
        <div data-controller="movie-cards-watch-list" data-movie-cards-watch-list-target="text" class="" style="display: flex">
          <input type="hidden" value="<%= movie.movie_name %>" data-add-watch-list-target="movie">
          <% if @watch_list.present? %>
            <% movie_added = false %>
            <% @watch_list.each do |movie_watch_list| %>
              <% if movie_watch_list.recommendation.movie_name == @recommendations[index].movie_name %>
                <a href="/user" class="movie-card-button movie-card-button-watch-list">
                  Is on your watch list
                </a>
                <% movie_added = true %>
                <% break %>
              <% end %>
            <% end %>
            <% unless movie_added %>
              <%= link_to "Add to your watch list", add_recommendations_to_watch_list_path(search_id: params[:id], id: movie.id), remote: true , data: {turbo_method: :post, action: "click->movie-cards-watch-list#acceptPopUp"}, class: "movie-card-button movie-card-button-watch-list" %>
            <% end %>
          <% else %>
            <%= link_to "Add to your watch list", add_recommendations_to_watch_list_path(search_id: params[:id], id: movie.id), remote: true , data: {turbo_method: :post, action: "click->add-watch-list#acceptPopUp"}, class: "movie-card-button movie-card-button-watch-list" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recommendations/index.html.erb
<%= render "shared/navbar" %>
<div class="container my-2 p-0 min-vh-100">
  <div class="prompt-container">
    <div class="bazzy-display">
      <%= image_tag "bazzy_avatar.png", alt: "Show case of BazzAI", id: "bazzy-index" %>
    </div>
    <div class="typewriter-container">
        <p>Hi there! It's your furry AI companion, Bazzy. I'm working tirelessly to find the perfect recommendation for you, tailoring it to your unique preferences and interests. Trust me, it'll be worth the wait!</p>
    </div>
  </div>
  <hr class="w-75"/>
  <div class="container d-flex">
    <div data-controller="view-more" class="d-flex flex-column align-item-start justify-content-start gap-4 w-100 my-4">
      <% @recommendations.each_with_index do |movie, index| %>
        <% if index < 3 %>
          <div data-view-more-target="cards" data-controller="omdb-request" class="d-flex flex-column align-item-center justify-content-center gap-3">
            <%= render "recommendations/movie_card",movie: movie, index: index %>
          </div>
        <% else %>
          <div data-view-more-target="cards" data-controller="omdb-request" class="d-flex flex-column align-item-center justify-content-center gap-3 d-none">
            <%= render "recommendations/movie_card", movie: movie, index: index %>
          </div>
        <% end %>
      <% end %>
      <div class="w-100 d-flex flex-wrap gap-3">
        <button data-view-more-target="more" data-action="click->view-more#more" class="view-button">View more</button>
        <button data-view-more-target="all" data-action="click->view-more#all" class="view-button">View all</button>
      </div>
    </div>
  </div>
</div>

app/views/recommendations/search.html.erb
<%= render "shared/navbar" %>
<div class="container p-0" data-controller="fake-background-job" data-fake-background-job-target="content">
  <div class="main-container">
    <br>
    <%# <h5>Guide Bazzy with your mood, available time, and genre preferences.</h5> %>
    <h5>Let Bazzy curate your perfect movie or TV show - all in a few clicks</h5>
    <br>
    <hr class="divider">
    <%= form_with(model: @query, url: search_path, method: :post, data: {action: "submit->fake-background-job#fakeSubmit"}) do |form| %>
      <%# Medium %>
      <h5>Choose a medium:</h5>
      <br>
      <%= form.fields_for :medium do |medium_form| %>
        <div class="row" data-controller="medium-selection" data-medium-selection-target="container">
          <div class="tag-item col-md-2 mb-4">
            <%= form.radio_button :medium, "Movie", { class: "tag-selector", style: "display: none;"} %>
            <%= form.label :medium_movie, "Movie" %>
          </div>
          <div class="tag-item col-md-2 mb-4">
            <%= form.radio_button :medium, "TV Show", { class: "tag-selector", style: "display: none;"} %>
            <%= form.label :medium_tv_show, "TV Show" %>
          </div>
        </div>
      <% end %>
      <br>
      <%# Time %>
      <h5>Got time to spare?</h5>
      <br>
      <div class="form-group d-flex flex-column flex-md-row align-items-center gap-3 w-100" data-controller="slider">
        <%= form.range_field :time, min: 15, max: 120, step: 5, class: "custom-range", data: { action: "change->slider#updateMinValue", slider_target: "input" }, name: "query[time]" %>
        <div>
        <span data-slider-target="output" class="text-center" style="display: inline-block"></span>
        <span></span>
        </div>
      </div>
      <hr class="divider">
      <%# Audience %>
      <br>
      <h5>Who's joining the fun?</h5>
      <br>
      <%= form.fields_for :medium do |medium_form| %>
        <div class="row" data-controller="medium-selection" data-medium-selection-target="container">
          <div class="tag-item col-md-2 mb-4">
            <%= form.radio_button :audience, "Just me", { class: "tag-selector", style: "display: none;"} %>
            <%= form.label :audience_just_me, "Just me" %>
          </div>
          <div class="tag-item col-md-2 mb-4">
            <%= form.radio_button :audience, "Couple", { class: "tag-selector", style: "display: none;"} %>
            <%= form.label :audience_couple, "Partner" %>
          </div>
          <div class="tag-item col-md-2 mb-4">
            <%= form.radio_button :audience, "Family", { class: "tag-selector", style: "display: none;"} %>
            <%= form.label :audience_family, "Family" %>
          </div>
        </div>
      <% end %>
      <hr class="divider">
      <%# Genre %>
      <h5> Favor Any Genres? </h5>
      <br>
      <%= form.fields_for :genre do |genre_form| %>
        <div class="row-g row"  data-controller="genre-selection" data-genre-selection-target="container">
          <% @genres.each_slice(6) do |genres_row| %>
            <div class="row-g row">
              <% genres_row.each do |genre| %>
                <div class="tag-item col-md-2 mb-4" data-controller="genre-selection" data-genre-selection-target="checkbox">
                  <%= genre_form.check_box genre.to_sym, { class: "tag-selector", style: "display: none;" , data: { action: "click->genre-selection#updateSelectedCount" }}, genre %>
                  <%= genre_form.label genre %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
      <%# Year %>
      <h5>Publishing Year</h5>
      <div class="d-flex">
        <div class="form-group w-25">
          <%= form.label :year_from, "From:" %>
          <%= form.number_field :year_after, value: 1950, in: 1925..2022, step: 1, class: 'form-control', placeholder: 1950 %>
        </div>
        <div class="form-group w-25">
          <%= form.label :year_before, "To:" %>
          <%= form.number_field :year_before, value: 2022, in: 1925..2022, step: 1, class: 'form-control', placeholder: 2023 %>
        </div>
      </div>
      <hr class="divider">
      <%# Mood Status Quo%>
      <h5>How do you feel?</h5>
      <br>
      <div class=" w-100">
        <div class="d-flex align-items-center justify-content-start gap-4">
          <h6>Current Mood</h6>
          <div class="help-icon mb-2">
            <i class="fa-solid fa-circle-question"></i>
            <div class="help-text">Tell us how you're feeling on a happiness scale going from "Miserable" to "Over the Moon"</div>
          </div>
        </div>
        <div class="form-group d-flex flex-column flex-md-row align-items-center gap-3 w-100" data-controller="slider">
          <%= form.range_field :happiness, min: 0, max: 10, data: { action: "change->slider#updateValue", slider_target: "input" } %>
          <div>
            <span data-slider-target="output" class="text-center" style="display: inline-block"></span>
            <span>/ 10</span>
          </div>
        </div>
      </div>
      <%# Mood Desired%>
      <div class=" w-100">
        <div class="d-flex align-items-center justify-content-start gap-4">
          <h6>Desired Mood</h6>
          <div class="help-icon mb-2">
            <i class="fa-solid fa-circle-question"></i>
            <div class="help-text">Tell us how you would like to feel on a happiness scale going from "Miserable" to "Over the Moon"</div>
          </div>
        </div>
        <div class="form-group d-flex flex-column flex-md-row align-items-center gap-3 w-100" data-controller="slider">
          <%= form.range_field :desired_happiness, min: 0, max: 10, data: { action: "change->slider#updateValue", slider_target: "input" } %>
          <div>
            <span data-slider-target="output" class="text-center" style="display: inline-block"></span>
            <span>/ 10</span>
          </div>
        </div>
      </div>
      <div class="divider"></div>
      <%# Intensity %>
      <div class=" w-100">
        <div class="d-flex align-items-center justify-content-start gap-4">
          <h6>Intensity</h6>
          <div class="help-icon mb-2">
            <i class="fa-solid fa-circle-question"></i>
            <div class="help-text">Tell us how much you want to focus on a scale of 1 to 10</div>
          </div>
        </div>
        <div class="form-group d-flex flex-column flex-md-row align-items-center gap-3 w-100" data-controller="slider">
          <%= form.range_field :intensity, min: 0, max: 10, data: { action: "change->slider#updateValue", slider_target: "input" } %>
          <div>
            <span data-slider-target="output" class="text-center" style="display: inline-block"></span>
            <span>/ 10</span>
          </div>
        </div>
      </div>
      <%# Novelty %>
      <div class=" w-100">
        <div class="d-flex align-items-center justify-content-start gap-4">
          <h6>Novelty</h6>
          <div class="help-icon mb-2">
            <i class="fa-solid fa-circle-question"></i>
            <div class="help-text">Tell us how experimental you want our suggestion to be on a scale of 1 to 10</div>
          </div>
        </div>
        <div class="form-group d-flex flex-column flex-md-row align-items-center gap-3 w-100" data-controller="slider">
          <%= form.range_field :novelty, min: 0, max: 10, data: { action: "change->slider#updateValue", slider_target: "input" } %>
          <div>
            <span data-slider-target="output" class="text-center" style="display: inline-block"></span>
            <span>/ 10</span>
          </div>
        </div>
      </div>
      <%# Recent Movies %>
      <hr class="divider">
      <h5>Something similar to: </h5>
      <%# Movie search start %>
      <div data-controller="movie-search">
        <div class="form-group">
          <%= form.label :recent_movie, "Search for a movie:" %>
          <%= form.text_field :search_movie, class: 'form-control', data: { action: 'keyup->movie-search#handleInput', movie_search_target: 'search' } %>
        </div>
        <br>
        <div class="search-boxes-container" data-movie-search-target="results">
        </div>
        <br>
        <div class="search-boxes-container select-movies">
          <div class="search-boxes-container-results-card" data-movie-search-target="selectedOne" data-action="click->movie-search#removeMovie" id="selected-one">
            <%= form.text_field :recent_movie1, value: "", class: "d-none", data: { target: "movie-search.recentOne" } %>
            <img src="https://cdn.discordapp.com/attachments/1105433122998325278/1116395162105552946/bazzy_avatar.png" class="search-boxes-container-results-card-image" />
            <p class="search-boxes-container-results-card-infos">
              Think of a movie or Tv show
            </p>
          </div>
          <div class="search-boxes-container-results-card" data-movie-search-target="selectedTwo" data-action="click->movie-search#removeMovie" id="selected-two">
            <%= form.text_field :recent_movie2, value: "", class: "d-none", data: { target: "movie-search.recentTwo" } %>
            <img src="https://cdn.discordapp.com/attachments/1105433122998325278/1116395162105552946/bazzy_avatar.png" class="search-boxes-container-results-card-image" />
            <p class="search-boxes-container-results-card-infos">
              Just start to type...
            </p>
          </div>
          <div class="search-boxes-container-results-card" data-movie-search-target="selectedThree" data-action="click->movie-search#removeMovie" id="selected-three">
            <%= form.text_field :recent_movie3, value: "", class: "d-none", data: { target: "movie-search.recentThree" } %>
            <img src="https://cdn.discordapp.com/attachments/1105433122998325278/1116395162105552946/bazzy_avatar.png" class="search-boxes-container-results-card-image" />
            <p class="search-boxes-container-results-card-infos">
              Choose up to three!
            </p>
          </div>
        </div>
      </div>
      <%# Movie search end %>
      <br>
      <%# Streaming Platforms %>
      <hr class="divider">
      <h5>Where do you want to watch?</h5>
      <br>
      <%= form.fields_for :streaming_platform do |streaming_platform_form| %>
        <div class="row">
          <div class="section">
            <div class="row">
              <% Query::STREAMING_PLATFORMS.each do |streaming_platform| %>
                <div class="streaming-item col-md-1 mb-4">
                  <%= streaming_platform_form.check_box streaming_platform.to_sym, { class: "streaming-selector d-none", disabled: false}, streaming_platform %>
                  <label for="query_streaming_platform_<%= streaming_platform %>">
                    <%= image_tag "#{streaming_platform}.png", class: "streaming-logo" %>
                  </label>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <%# Other %>
      <hr class="divider">
      <h5>Anything else we should know?</h5>
      <p style="font-size: 20px;">Feel free to write your heart out</p>
      <br>
      <div class="form-group">
        <%= form.text_area :other, class: "form-text-area" %>
      </div>
      <hr class="divider">
      <div class= "mb-4">
        <%= form.submit "Search", class: "search-button" %>
      </div>
    <% end %>
  </div>
</div>