config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get '/search', to: 'recommendations#search'
  post '/search', to: 'recommendations#create'

  get '/search/:id/recommendations', to: 'recommendations#index', as: 'search_result'
  get '/search/:id/recommendations/:id', to: 'recommendations#show', as: 'search_result_details'
  delete '/search/:search_id/recommendations/:id/delete', to: 'recommendations#destroy', as: 'destroy_recommendation'
  post '/search/:id/recommendations/:id', to: 'recommendations#add_recommendations', as: 'add_recommendations_to_watch_list'

  get '/user', to: 'pages#user_page', as: 'watchlist'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container container-fluid d-flex justify-content-between align-items-center container-footer">
    <div>
      <p class= "text-start">©Bazzy</p>
    </div>

    <div>
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></
      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></
      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></
      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></
      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></
      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="main-nav-bar">
  <div class="container container-fluid d-flex justify-content-between align-items-center container-nav-bar">
    <div class="d-flex justify-content-center align-items-center gap-3">
      <%= link_to search_path, class: "text-decoration-none" do %>
        <h1 class="logo1 font-size-30">Movie Mate</h1>
      <% end %>
      <% if action_name == 'show' %>
        <%= link_to :back, class: "back-button" do %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
      <% end %>
    </div>
    <div class="" id="navbarSupportedContent">
      <ul class="d-flex justify-content-center align-items-center gap-3 mb-0 list-style-none">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to watchlist_path, data: {turbo_method: :get}, class: "avatar" do %>
              <%= image_tag "bazzy_avatar.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "login-button" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "sign-up-button" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>