config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get '/search', to: 'recommendations#search'
  post '/search', to: 'recommendations#create'

  get '/search/:id/recommendations', to: 'recommendations#index', as: 'search_result'
  get '/search/:id/recommendations/:id', to: 'recommendations#show', as: 'search_result_details'
  delete '/search/:search_id/recommendations/:id/delete', to: 'recommendations#destroy', as: 'destroy_recommendation'
  post '/search/:id/recommendations/:id', to: 'recommendations#add_recommendations', as: 'add_recommendations_to_watch_list'

  get '/user', to: 'pages#user_page', as: 'watchlist'
end

app/models/query.rb
class Query < ApplicationRecord
  belongs_to :user
  has_many :recommendations
  MEDIUMS = ["Movie", "TV Show"]
  AUDIENCE = ["Just Me", "Couple", "Family"]
  STREAMING_PLATFORMS = ["netflix", "hulu", "prime", "hbo", "disney", "apple", "peacock", "youtube", "wow", "mubi"]
  GENRES = [
    "Acclaimed",
    "Action",
    "Adventure",
    "Animation",
    "Anime",
    "Biography",
    "Classic",
    "Comedy",
    "Crime",
    "Cult",
    "Documentary",
    "Drama",
    "Experimental",
    "Family",
    "Fantasy",
    "Film-Noir",
    "Gangster",
    "History",
    "Horror",
    "Independent",
    "International",
    "Music",
    "Mystery",
    "Musical",
    "Noir",
    "Psychological",
    "Queer",
    "Reality",
    "Romance",
    "Rom-Com",
    "Satire",
    "Sci-Fi",
    "Space",
    "Sports",
    "Spy",
    "Superhero",
    "Supernatural",
    "Suspense",
    "Thriller",
    "True Crime",
    "Western",
    "Youth"
  ]
  MOOD = [
    "Depressed",
    "Sad",
    "Melancholic",
    "Bummed Out",
    "Pensive",
    "Okay",
    "Chill",
    "Neutral",
    "Happy",
    "Excited",
    "Thrilled",
    "Over the Moon"
  ]
end

app/views/pages/_movie_card.html.erb
<% if movie['movie_name'] != nil %>
<div class="movie-card movie-card-user-page <%= watch_list ? 'movie-card-user-page-watch-list' : '' %>">
  <%= image_tag movie['image'] && movie['image'] != 'N/A' ? movie['image'] : '', alt: movie['movie_name']  %>
  <div class="movie-card-infos-container">
    <h1 class="movie-card-infos-container-title"><%= movie['movie_name'] %> ( <%= movie['year'] %> )</h1>
    <p class="movie-card-infos-container-description"><%= movie['synopsis'] && movie['synopsis'] != 'N/A' ? movie['synopsis'] : "The #{ movie['movie_name'] } no have description for now!" %></p>
    <div class="movie-card-infos-container-buttons-container">
      <%= link_to "Learn more", "/search/#{movie.query.id}/recommendations/#{movie.id}", class: "movie-card-infos-container-buttons-container-button"%>
    </div>
  </div>
</div>
<% end %>

app/views/pages/home.html.erb
<div class="home-page d-flex flex-column justify-content-center align-items-center vh-100 bg-dark">
  <div class="container home-page-container">
    <h1 class="logo1 font-size-70 mt-3">Movie Mate</h1>
    <h2 class="text-center font-weight-bold mb-0">Finally Recommendations That Don't Suck</h2>
    <div class="home-page-buttons-container">
      <%= link_to "Find Your Match", search_path, class: "magic-button text-decoration-none mb-4" %>
    </div>
    <div class="transparent-box">
      <%= image_tag "bazzy_avatar.png", alt: "Image 1", class: "bazzy" %>
      <div class= "left-container">
        <button class="hover-button text-center">Set your preferences</button>
        <button class="hover-button text-center">Let Bazzy do the work</button>
        <button class="hover-button text-center">AI magic</button>
        <button class="hover-button text-center">Sit back and enjoy</button>
      </div>
      <div class="right-container">
        <div class="background-container d-flex flex-column align-items-center">
          <h1 class= "pt-3">Bazzy's picks</h1>
          <hr class="divider">
          <div class="movie-box">
            <button class="close-button">&times;</button>
            <div class="content">
              <img src="https://lwlies.com/wp-content/uploads/2016/06/TheWindRisesPoster-900x0-c-default.jpg" alt="Image 1">
              <div class="info" data-controller="typewriter">
                <p class="h7" data-typewriter-target="text" data-typewriter-delay="0">The Wind Rises (2013)</p>
                <p class= "p" data-typewriter-target="text" data-typewriter-delay="500">A look at the life of Jiro Horikoshi, the man who designed Japanese fighter planes during World War II.</p>
                <button class="button" data-typewriter-target="text" data-typewriter-delay="2800">Learn more</button>
                <button class="button" data-typewriter-target="text" data-typewriter-delay="2900">More like this</button>
              </div>
            </div>
          </div>

          <div class="movie-box">
            <button class="close-button">&times;</button>
            <div class="content">
              <img src="https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png" alt="Image 2">
              <div class="info" data-controller="typewriter">
                <p class="h7" data-typewriter-target="text" data-typewriter-delay="3000">Your Name. (2016)</p>
                <p class= "p" data-typewriter-target="text" data-typewriter-delay="3200">Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.</p>
                <button class="button" data-typewriter-target="text" data-typewriter-delay="5400">Learn more</button>
                <button class="button" data-typewriter-target="text" data-typewriter-delay="5500">More like this</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/user_page.html.erb
<%= render "shared/navbar" %>
<div class="min-vh-100 w-100">
  <% if @querys.length > 0  %>
    <div class="d-flex align-items-center justify-content-center flex-column container min-vh-100 w-100 p-0">
      <div class="container d-flex flex-column w-100 position-relative">
        <div data-controller="cards-slider" class="d-flex align-items-center justify-content-start overflow-hidden w-100 gap-3 py-4">
          <button data-action="click->cards-slider#leftSlide" class="left-button slider-button" disabled="true"><%= '<' %></button>
          <div data-cards-slider-target="slide" class="d-flex align-items-center justify-content-start gap-3 py-4 position-relative" style="transform: translateX(0px);">
            <% @querys.each_with_index do |query,index| %>
              <a href="#query<%= query.id %>" class="clash-card barbarian">
              <% @image = Recommendation.find(query.recommendation_ids[0]).image %>
                <div class="clash-card__image clash-card__image--barbarian w-100" style="position: relative; align-items: center; display: flex; justify-content: center; flex-direction: column; height: 230px; margin-bottom: 35px; border-top-left-radius: $border-radius-size; border-top-right-radius: $border-radius-size; background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('<%= @image %>'); background-size: cover;">
                  <%= image_tag "bazzy_avatar.png", alt: "Bazzy", style: "width: 300px; position: absolute;" %>
                </div>
                <div class="d-flex flex-column align-items-center justify-content-start" style="min-height:200px">
                  <div class="clash-card__level clash-card__level--barbarian w-100">Search <%= index + 1 %></div>
                  <div class="clash-card__unit-name text-capitalize w-100"><%= query.medium ? query.medium : "Movie / TV Show" %></div>
                  <div class="clash-card__unit-description w-100">
                    <div>
                      <div class="clash-card__level clash-card__level--barbarian w-100"></div>
                      <div class="d-flex flex-wrap my-1 align-items-start justify-content-center gap-1">
                        <% if query.genre.split(', ').length > 0 %>
                          <% query.genre.split(', ').each_with_index do |genre, index| %>
                            <% if index < 2 %>
                              <span class="genre-button-query">
                                <%= genre %>
                              </span>
                            <% end %>
                          <% end %>
                        <% else %>
                          <span class="genre-button-query">
                            No Genres
                          </span>
                        <% end %>
                      </div>
                    </div>
                    <br>
                    <div>
                      <div class="clash-card__level clash-card__level--barbarian w-100"></div>
                      <div class="d-flex flex-wrap my-1 align-items-center justify-content-center gap-2">
                        <span class="">
                          <%= query.year_after %>
                        </span>
                        -
                        <span class="">
                          <%= query.year_before %>
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="clash-card__unit-stats clash-card__unit-stats--barbarian clearfix w-100">
                  <div class="one-third">
                    <div class="stat"><%= query.time %></div>
                    <div class="stat-value">Minutes</div>
                  </div>
                  <div class="one-third">
                    <div class="stat"><%= query.intensity %>/10</div>
                    <div class="stat-value">Intensity</div>
                  </div>
                  <div class="one-third no-border">
                    <div class="stat"><%= query.novelty %>/10</div>
                    <div class="stat-value">Novelty</div>
                  </div>
                </div>
              </a>
            <% end %>
          </div>
          <button data-action="click->cards-slider#rightSlide" class="right-button slider-button"><%= '>' %></button>
        </div>
      </div>
      <h3>Your Watch List:</h3>
      <hr/>
      <div class="container d-flex flex-column w-100 position-relative">
        <div data-controller="cards-slider" class="d-flex align-items-center justify-content-start overflow-hidden w-100 gap-3 py-4">
          <button data-action="click->cards-slider#leftSlide" class="left-button slider-button" disabled="true"><%= '<' %></button>
          <div data-cards-slider-target="slide" class="d-flex align-items-center justify-content-start gap-3 py-4 position-relative" style="transform: translateX(0px);">
            <% @watch_list.reverse.each do |movie| %>
              <%= render "pages/movie_card", movie: movie, watch_list: true %>
            <% end %>
          </div>
          <button data-action="click->cards-slider#rightSlide" class="right-button slider-button"><%= '>' %></button>
        </div>
      </div>
      <h3>Your Previous Recommendations:</h3>
      <hr/>
      <div class="container d-flex flex-column w-100 position-relative gap-3">
        <% @querys.reverse.each_with_index do |query,index| %>
          <h3>Bazzy's Picks: <%= @querys.length - index %> of <%= @querys.length %></h3>
          <hr/>
          <div class="prompt-container">
            <div class="bazzy-display">
              <%= image_tag "bazzy_avatar.png", alt: "Show case of BazzAI", id: "bazzy-index" %>
            </div>
            <div class="typewriter-container">
              <div style="font-family: 'poppins'; font-size: 18px">
                <%= @display_prompts[index] %>
              </div>
            </div>
          </div>
          <div data-controller="cards-slider" class="d-flex align-items-center justify-content-start overflow-hidden w-100 gap-3 py-4">
            <button data-action="click->cards-slider#leftSlide" class="left-button slider-button" disabled="true"><%= '<' %></button>
            <div id="query<%= query.id %>" data-cards-slider-target="slide" class="d-flex align-items-center justify-content-start gap-3 py-4 position-relative" style="transform: translateX(0px);">
              <% @recommendations.each do |recommendation| %>
                <% if recommendation.query_id == query.id %>
                  <%= render "pages/movie_card", movie: recommendation, watch_list: false %>
                <% end %>
              <% end %>
            </div>
            <button data-action="click->cards-slider#rightSlide" class="right-button slider-button"><%= '>' %></button>
          </div>
          <%= link_to "View query page", "/search/#{query.id}/recommendations", class: 'add-button add-button-log-out' %>
        <% end %>
      </div>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "add-button add-button-log-out" %>
    </div>
  </div>
<% else %>
  <div class="container p-0">
    <h1>No searches yet</h1>
  </div>
<% end %>
</div>